version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=yacht_db
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: app-api
    entrypoint: entrypoint
    build:
      context: ./
    # image: quotes-api
    depends_on:
      - db
    ports:
      - 3000:3000
    # environment:
    #   NODE_ENV: production
        DB_HOST: host.docker.internal
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_NAME: postgres
    links:
      - db
    volumes:
      - "./:/src"
volumes:
  db:
    driver: local
